hello: "기본 옵션입니다.지정한 프로필과 같이 출력됩니다" #모든프로필에 추가적으로 나온다.프로필 defualt로 지정하면 이것만 출력됨

--- #프로필 구분자
spring:
  profiles: dev
hellod: "개발옵션입니다."

---
spring:
  profiles: test
hellot: "테스트옵션입니다."

---
spring:
  profiles: act
helloa: "가동옵션입니다."
